sources:
  yahoo: false
  finnhub: true
  moex: false


## Metrics - pe_ratio, pb_ratio, roeTTM, roaTTM, roiTTM, net_margin, dividend_yield, eps_ttm

metrics:
  include:
    - pe_ratio
    - pb_ratio
    - roeTTM
    - roaTTM
    - roiTTM
    - net_margin
    - dividend_yield
    - eps_ttm
    - pfcfShareTTM
    

defaults:
  currency: USD
  region: US
