sources:
  yahoo: false
  finnhub: true
  moex: false


## Metrics - pe_ratio, pb_ratio, roeTTM, roaTTM, roiTTM, net_margin, dividend_yield, eps_ttm

metrics:
  include:
    - pe_ratio
    - pb_ratio
    - roeTTM
    - roaTTM
    - roiTTM
    - net_margin
    - dividend_yield
    - eps_ttm
    - pfcfShareTTM
    - longTermDebt/equityAnnual
    - epsGrowth5Y
    - revenueGrowth5Y
    - beta
    - payoutRatioAnnual
    - grossMarginAnnual
    - currentRatioAnnual
    - dividendGrowthRate5Y
    

defaults:
  currency: USD
  region: US
